apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vidp

# Ordre de d√©ploiement
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - langscale.yaml
  - downscale.yaml
  - subtitle.yaml
  - animal-detect.yaml
  - aggregation.yaml
  - main-app.yaml
  - frontend.yaml
  - ingress.yaml

# Labels communs
commonLabels:
  project: vidp
  environment: development

# Annotations communes
commonAnnotations:
  description: "VidP Video Processing Platform"
