apiVersion: v1
kind: Secret
metadata:
  name: vidp-secrets
  namespace: vidp
type: Opaque
stringData:
  MONGODB_USERNAME: "vidp_admin"
  MONGODB_PASSWORD: "vidp_password_2024"
  MONGODB_URL: "mongodb://vidp_admin:vidp_password_2024@mongodb-service:27017/vidp_db?authSource=admin"
